### ISSUE TITLE
Unknown status! - Check Game window!

### ISSUE THREAD

**Issue by schwipschwap** [JumpY2k3/WoWNotifier#1]
Did not work with DirectX 12 option active. The screenshot was all blacked out. Switching to DirectX 11 solved the problem.

**Comment by pyx1337** [comment]
> Did not work with DirectX 12 option active. The screenshot was all blacked out. Switching to DirectX 11 solved the problem.

Perfect! Was working on the same issue, was debugging function Get-WoWQueue but switching to DX11 is way easier, thanks!

**Comment by JumpY2k3** [comment]
> > Did not work with DirectX 12 option active. The screenshot was all blacked out. Switching to DirectX 11 solved the problem.
> 
> Perfect! Was working on the same issue, was debugging function Get-WoWQueue but switching to DX11 is way easier, thanks!

Oh okay, I have only DirectX 11. Where did you change the DX12 to DX11? May I can fix this in the code that it is working for both DX12 and DX11.

**Comment by schwipschwap** [comment]
Ingame Options. System > Advanced > Graphics API

**Comment by roaspeci** [comment]
Yes had the same problem on Win11 but after switching to direct x 11 it does work!

great work thank you very much! Do you think, you could also implement the feature to let it run but if there is a "disconnect" out of the game to have a reminder? That would help if i leave the computer alone for some minutes. Thanks!

**Comment by JumpY2k3** [comment]
> Yes had the same problem on Win11 but after switching to direct x 11 it does work!
> 
> great work thank you very much! Do you think, you could also implement the feature to let it run but if there is a "disconnect" out of the game to have a reminder? That would help if i leave the computer alone for some minutes. Thanks!

You are talking from the active game? So when you are ingame and dropped out of game? (Like Anti-AFK?) It is possible, but I think this is against the ToS of Blizzard/WoW :/

**Comment by roaspeci** [comment]
No i don't mean to act anyway to prevent the afk - just to be informed. I have around 1-2 disconnects straight from the game in ~4h and then you only have 5 Mins to get back before you will have to pass the Queue again. So it would be very helpful to have the "check" and the "bell" everytime the OCR reads "Reconnect"

**Comment by JumpY2k3** [comment]
Yes, but you are talking about "active game" into character window / disconnect from Server. It would be possible if the screenshot and ocr is adjusted. 
Problem: If anywhere on the screen is the word "Reconnect or Disconnected", it will send an alert. (Also on the chat window!)

I have ideas for this, but still struggling about a tool like this..

**Comment by roaspeci** [comment]
True that could be funny :) the snippet must be very accurat in the middle
then but maybe not the best idea :)

Am Di., 4. Okt. 2022 um 20:36 Uhr schrieb JumpY2k3 ***@***.***

**Comment by pyx1337** [comment]
Wouldn't it be possible to first store the last state?
Que to Login screen vs in-game to Login screen?

Maybe with an in-game weak aura with a specific text?

roaspeci ***@***.***> schrieb am Di., 4. Okt. 2022, 20:48:

**Comment by JumpY2k3** [comment]
That would be my workaround for this situation. Maybe creating a Weakaura which is alway visible with the text "ThisStringMeansIamConnected" and search for this text. If not visible -> Alert. Best way would to use only specific screenshot area, that is possible with another screenshot routine without searching for the process. (The Game must be in foreground then)

This would my solution, if anyone want to adjust my code, feel free. At this point, I don't want to publish this.

**Comment by AlsenDev** [comment]
This might be relevant to some, but I had the same problem while using DirectX 11. My screenshots were all white. I suspected this might be because of running it on an old notebook with Intel HD graphics in windowed mode.

I fixed it by changing the 'nFlags' parameter of the PrintWindow method to 2 instead of 0. 

Got the idea from a comment in this thread: https://stackoverflow.com/questions/69605967/c-printwindow-api-returns-black-or-partial-images-alternative-methods _"The PW_RENDERFULLCONTENT flag is undocumented, but works starting in Windows 8.1. It allows for capturing the contents of the window that are drawn using DirectComposition."_

**Comment by JumpY2k3** [comment]
@schwipschwap @pyx1337 @roaspeci 
Could you check the information from @AlsenDev out? 

It should be Line 181: [User32]::PrintWindow($proc.MainWindowHandle, $hdcBitmap, 0)
change to: [User32]::PrintWindow($proc.MainWindowHandle, $hdcBitmap, 2)

I tested it in DX11, it's still working. May it will work on DX12 then. That would be a great fix!

**Comment by roaspeci** [comment]
Yes it worked for me... After I upgraded to win 11h2 it didn't worked with
dx11 but after the change its okay now.

Tough I transfered today because of the queue so can't test anymore :-)

JumpY2k3 ***@***.***> schrieb am Do., 6. Okt. 2022, 21:46:

**Comment by JumpY2k3** [comment]
> Yes it worked for me... After I upgraded to win 11h2 it didn't worked with dx11 but after the change its okay now. Tough I transfered today because of the queue so can't test anymore :-)

You could try without queue: Start it, the screenshot is saved to the program directory. If its not black, it's working :)

**Comment by schwipschwap** [comment]
With @AlsenDev's change the images are not black anymore on DirectX12.

**Comment by JumpY2k3** [comment]
Thank you for your idea and the tests of the other. I will change this in the code.
